#!/bin/bash

echo if \[ -d \"\$HOME/bin\" \] \; then >> ~/.profile2
echo "  "PATH=\"\$HOME/bin:\$PATH\" >> ~/.profile2
echo fi >> ~/.profile2
echo "" >> ~/.profile2
grep -v "#" ~/.profile >> ~/.profile2
mv ~/.profile2 ~/.profile

echo "" >> ~/.bashrc
echo export GCC_COLORS=\'error=01\;31:warning=01\;35:note=01\;36:caret=01\;32:locus=01:quote=01\' >> ~/.bashrc
echo "" >> ~/.bashrc
echo export LS_OPTIONS=\'--color=auto\' >> ~/.bashrc
echo eval \"\`dircolors\`\" >> ~/.bashrc
echo alias ls=\'ls \$LS_OPTIONS\' >> ~/.bashrc
echo alias ll=\'ls \$LS_OPTIONS -lh\' >> ~/.bashrc
echo alias la=\'ls \$LS_OPTIONS -lha\' >> ~/.bashrc
echo alias grep=\'grep --color=auto\' >> ~/.bashrc

mkdir ~/bin
echo git clone https://github.com/e253834/\$1.git > ~/bin/roll
echo cd \$1 >> ~/bin/roll
echo bash ./doit >> ~/bin/roll
chmod +x ~/bin/roll
